// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAR38TXHtVjgnLcjMC65tSA1c-MwxHFyzE',
    appId: '1:54729299977:web:6366fc93f60fc81f0e00d8',
    messagingSenderId: '54729299977',
    projectId: 'vipcar-v1',
    authDomain: 'vipcar-v1.firebaseapp.com',
    storageBucket: 'vipcar-v1.firebasestorage.app',
    measurementId: 'G-87FX94LG2C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUlkg_6UIgsm10-eUQM1MREJckJeqQfJo',
    appId: '1:54729299977:android:653385570e9964a40e00d8',
    messagingSenderId: '54729299977',
    projectId: 'vipcar-v1',
    storageBucket: 'vipcar-v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZKIq_kx4whavH6SQ4oYsWUZDp6r9hgtA',
    appId: '1:54729299977:ios:2912cccfbebcb7920e00d8',
    messagingSenderId: '54729299977',
    projectId: 'vipcar-v1',
    storageBucket: 'vipcar-v1.firebasestorage.app',
    iosBundleId: 'com.example.vipcarV1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZKIq_kx4whavH6SQ4oYsWUZDp6r9hgtA',
    appId: '1:54729299977:ios:2912cccfbebcb7920e00d8',
    messagingSenderId: '54729299977',
    projectId: 'vipcar-v1',
    storageBucket: 'vipcar-v1.firebasestorage.app',
    iosBundleId: 'com.example.vipcarV1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAR38TXHtVjgnLcjMC65tSA1c-MwxHFyzE',
    appId: '1:54729299977:web:89a70b7bc06b386a0e00d8',
    messagingSenderId: '54729299977',
    projectId: 'vipcar-v1',
    authDomain: 'vipcar-v1.firebaseapp.com',
    storageBucket: 'vipcar-v1.firebasestorage.app',
    measurementId: 'G-CQX9ZD7354',
  );
}
